# https://help.github.com/en/articles/workflow-syntax-for-github-actions
# https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions

name: Continuous Deployment

on:
  push:
    branches:
      - master
      - '*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  linux:
    #if: github.actor && secrets['HAKUNEKO_PASSPHRASE']
    name: Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
        timeout-minutes: 5

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
        timeout-minutes: 5

      - name: Install NPM Packages
        timeout-minutes: 10
        run: npm install

      - name: Security Audit
        timeout-minutes: 5
        run: npm audit --audit-level=high || true

      - name: Lint
        timeout-minutes: 10
        run: npm run lint

      # Tests are currently disabled, because they do not work properly (unreliable)
      #- name: Test
      #  run: npm run test

      - name: Deploy (web)
        timeout-minutes: 30
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HAKUNEKO_TOKEN: ${{ secrets.HAKUNEKO_ACCESS_TOKEN }}
          HAKUNEKO_PASSPHRASE: ${{ secrets.HAKUNEKO_PASSPHRASE }}
          # set variable with branch that triggered the action (e.g. GITHUB_BRANCH = ${{ github.ref }})
        run: npm run deploy:web
